// Generated by nuxt-echarts

import type { ComposeOption } from 'echarts/core'
import type {
  LineSeriesOption,
} from 'echarts/charts'
import type {
  DatasetComponentOption,
  GridComponentOption,
} from 'echarts/components'

declare global {
  export type ECOption = ComposeOption<
    | LineSeriesOption
    | DatasetComponentOption
    | GridComponentOption
  >
}

export {}