// Generated by nuxt-echarts

import { use } from 'echarts/core'
import {
  SVGRenderer,
  CanvasRenderer,
} from 'echarts/renderers'
import {
  LineChart,
} from 'echarts/charts'
import {
  DatasetComponent,
  GridComponent,
} from 'echarts/components'
import {

} from 'echarts/features'

use([
  SVGRenderer,
  CanvasRenderer,
  LineChart,
  DatasetComponent,
  GridComponent,

])